// import json

// # Sample data for all countries with ISO 3166-1 alpha-2 codes, country names, and currencies
// # Note: This is a simplified mapping for demonstration purposes. Currency mappings may not cover all dependencies or territories.

const country_data = [

    
  { "country": "Australia", "currency": "Australian Dollar", "alphaCode": "AU", "currencyCode": "AUD" },
  { "country": "Bulgaria", "currency": "Bulgarian Lev", "alphaCode": "BG", "currencyCode": "BGN" },
  { "country": "Brazil", "currency": "Brazilian Real", "alphaCode": "BR", "currencyCode": "BRL" },
  { "country": "Canada", "currency": "Canadian Dollar", "alphaCode": "CA", "currencyCode": "CAD" },
  { "country": "Switzerland", "currency": "Swiss Franc", "alphaCode": "CH", "currencyCode": "CHF" },
  { "country": "China", "currency": "Chinese Yuan", "alphaCode": "CN", "currencyCode": "CNY" },
  { "country": "Czech Republic", "currency": "Czech Koruna", "alphaCode": "CZ", "currencyCode": "CZK" },
  { "country": "Denmark", "currency": "Danish Krone", "alphaCode": "DK", "currencyCode": "DKK" },
  { "country": "Eurozone", "currency": "Euro", "alphaCode": "EU", "currencyCode": "EUR" },
  { "country": "United Kingdom", "currency": "British Pound", "alphaCode": "GB", "currencyCode": "GBP" },
  { "country": "Hong Kong", "currency": "Hong Kong Dollar", "alphaCode": "HK", "currencyCode": "HKD" },
  { "country": "Hungary", "currency": "Hungarian Forint", "alphaCode": "HU", "currencyCode": "HUF" },
  { "country": "Indonesia", "currency": "Indonesian Rupiah", "alphaCode": "ID", "currencyCode": "IDR" },
  { "country": "Israel", "currency": "Israeli New Shekel", "alphaCode": "IL", "currencyCode": "ILS" },
  { "country": "India", "currency": "Indian Rupee", "alphaCode": "IN", "currencyCode": "INR" },
  { "country": "Iceland", "currency": "Icelandic Króna", "alphaCode": "IS", "currencyCode": "ISK" },
  { "country": "Japan", "currency": "Japanese Yen", "alphaCode": "JP", "currencyCode": "JPY" },
  { "country": "South Korea", "currency": "South Korean Won", "alphaCode": "KR", "currencyCode": "KRW" },
  { "country": "Mexico", "currency": "Mexican Peso", "alphaCode": "MX", "currencyCode": "MXN" },
  { "country": "Malaysia", "currency": "Malaysian Ringgit", "alphaCode": "MY", "currencyCode": "MYR" },
  { "country": "Norway", "currency": "Norwegian Krone", "alphaCode": "NO", "currencyCode": "NOK" },
  { "country": "New Zealand", "currency": "New Zealand Dollar", "alphaCode": "NZ", "currencyCode": "NZD" },
  { "country": "Philippines", "currency": "Philippine Peso", "alphaCode": "PH", "currencyCode": "PHP" },
  { "country": "Poland", "currency": "Polish Zloty", "alphaCode": "PL", "currencyCode": "PLN" },
  { "country": "Romania", "currency": "Romanian Leu", "alphaCode": "RO", "currencyCode": "RON" },
  { "country": "Sweden", "currency": "Swedish Krona", "alphaCode": "SE", "currencyCode": "SEK" },
  { "country": "Singapore", "currency": "Singapore Dollar", "alphaCode": "SG", "currencyCode": "SGD" },
  { "country": "Thailand", "currency": "Thai Baht", "alphaCode": "TH", "currencyCode": "THB" },
  { "country": "Turkey", "currency": "Turkish Lira", "alphaCode": "TR", "currencyCode": "TRY" },
  { "country": "South Africa", "currency": "South African Rand", "alphaCode": "ZA", "currencyCode": "ZAR" },
  { "country": "United States", "currency": "US Dollar", "alphaCode": "US", "currencyCode": "USD" }

];
    // {"code": "af", "name": "Afghanistan", "currency": "afn"},
    // {"code": "al", "name": "Albania", "currency": "all"},
    // {"code": "dz", "name": "Algeria", "currency": "dzd"},
    // {"code": "ad", "name": "Andorra", "currency": "eur"},
    // {"code": "ao", "name": "Angola", "currency": "aoa"},
    // {"code": "ar", "name": "Argentina", "currency": "ars"},
    // {"code": "am", "name": "Armenia", "currency": "amd"},
    // {"code": "au", "name": "Australia", "currency": "aud"},
    // {"code": "at", "name": "Austria", "currency": "eur"},
    // {"code": "az", "name": "Azerbaijan", "currency": "azn"},
    // {"code": "bh", "name": "Bahrain", "currency": "bhd"},
    // {"code": "bd", "name": "Bangladesh", "currency": "bdt"},
    // {"code": "by", "name": "Belarus", "currency": "byn"},
    // {"code": "be", "name": "Belgium", "currency": "eur"},
    // {"code": "bz", "name": "Belize", "currency": "bzd"},
    // {"code": "bj", "name": "Benin", "currency": "xof"},
    // {"code": "bt", "name": "Bhutan", "currency": "btn"},
    // {"code": "bo", "name": "Bolivia", "currency": "bob"},
    // {"code": "ba", "name": "Bosnia and Herzegovina", "currency": "bam"},
    // {"code": "bw", "name": "Botswana", "currency": "bwp"},
    // {"code": "br", "name": "Brazil", "currency": "brl"},
    // {"code": "bn", "name": "Brunei", "currency": "bnd"},
    // {"code": "bg", "name": "Bulgaria", "currency": "bgn"},
    // {"code": "bf", "name": "Burkina Faso", "currency": "xof"},
    // {"code": "bi", "name": "Burundi", "currency": "bif"},
    // {"code": "kh", "name": "Cambodia", "currency": "khr"},
    // {"code": "cm", "name": "Cameroon", "currency": "xaf"},
    // {"code": "ca", "name": "Canada", "currency": "cad"},
    // {"code": "td", "name": "Chad", "currency": "xaf"},
    // {"code": "cl", "name": "Chile", "currency": "clp"},
    // {"code": "cn", "name": "China", "currency": "cny"},
    // {"code": "co", "name": "Colombia", "currency": "cop"},
    // {"code": "cr", "name": "Costa Rica", "currency": "crc"},
    // {"code": "hr", "name": "Croatia", "currency": "eur"},
    // {"code": "cu", "name": "Cuba", "currency": "cup"},
    // {"code": "cy", "name": "Cyprus", "currency": "eur"},
    // {"code": "cz", "name": "Czech Republic", "currency": "czk"},
    // {"code": "dk", "name": "Denmark", "currency": "dkk"},
    // {"code": "eg", "name": "Egypt", "currency": "egp"},
    // {"code": "et", "name": "Ethiopia", "currency": "etb"},
    // {"code": "fi", "name": "Finland", "currency": "eur"},
    // {"code": "fr", "name": "France", "currency": "eur"},
    // {"code": "de", "name": "Germany", "currency": "eur"},
    // {"code": "gh", "name": "Ghana", "currency": "ghs"},
    // {"code": "gr", "name": "Greece", "currency": "eur"},
    // {"code": "in", "name": "India", "currency": "inr"},
    // {"code": "id", "name": "Indonesia", "currency": "idr"},
    // {"code": "ir", "name": "Iran", "currency": "irr"},
    // {"code": "iq", "name": "Iraq", "currency": "iqd"},
    // {"code": "ie", "name": "Ireland", "currency": "eur"},
    // {"code": "il", "name": "Israel", "currency": "ils"},
    // {"code": "it", "name": "Italy", "currency": "eur"},
    // {"code": "jp", "name": "Japan", "currency": "jpy"},
    // {"code": "ke", "name": "Kenya", "currency": "kes"},
    // {"code": "kr", "name": "South Korea", "currency": "krw"},
    // {"code": "my", "name": "Malaysia", "currency": "myr"},
    // {"code": "mx", "name": "Mexico", "currency": "mxn"},
    // {"code": "ma", "name": "Morocco", "currency": "mad"},
    // {"code": "np", "name": "Nepal", "currency": "npr"},
    // {"code": "nz", "name": "New Zealand", "currency": "nzd"},
    // {"code": "ng", "name": "Nigeria", "currency": "ngn"},
    // {"code": "no", "name": "Norway", "currency": "nok"},
    // {"code": "pk", "name": "Pakistan", "currency": "pkr"},
    // {"code": "ph", "name": "Philippines", "currency": "php"},
    // {"code": "pl", "name": "Poland", "currency": "pln"},
    // {"code": "pt", "name": "Portugal", "currency": "eur"},
    // {"code": "qa", "name": "Qatar", "currency": "qar"},
    // {"code": "ro", "name": "Romania", "currency": "ron"},
    // {"code": "ru", "name": "Russia", "currency": "rub"},
    // {"code": "sa", "name": "Saudi Arabia", "currency": "sar"},
    // {"code": "sg", "name": "Singapore", "currency": "sgd"},
    // {"code": "za", "name": "South Africa", "currency": "zar"},
    // {"code": "es", "name": "Spain", "currency": "eur"},
    // {"code": "lk", "name": "Sri Lanka", "currency": "lkr"},
    // {"code": "se", "name": "Sweden", "currency": "sek"},
    // {"code": "ch", "name": "Switzerland", "currency": "chf"},
    // {"code": "th", "name": "Thailand", "currency": "thb"},
    // {"code": "tr", "name": "Turkey", "currency": "try"},
    // {"code": "ua", "name": "Ukraine", "currency": "uah"},
    // {"code": "ae", "name": "United Arab Emirates", "currency": "aed"},
    // {"code": "gb", "name": "United Kingdom", "currency": "gbp"},
    // {"code": "us", "name": "United States", "currency": "usd"},
    // {"code": "vn", "name": "Vietnam", "currency": "vnd"}


export default country_data;

// # Add flag URLs
// for country in country_data:
//     country["flag"] = f"https://countryflagsapi.com/png/{country['code']}"

// json_output = json.dumps(country_data, indent=2)
// json_output[:1000]  # Display only the first 1000 characters for preview here
